# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "VHT"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

session:  "YAML"
template: "template_toolkit"
logger:   "File"

engines:
   template:
     template_toolkit:
       encoding:  'utf8'
       start_tag: '[%'
       end_tag:   '%]'

   session:
     YAML:
       cookie_name: vht.session
       is_secure: 0
       is_http_only: 1

   logger:
     File:
       log_level: debug

plugins:
   Database:
      driver: 'Pg'
      database: vht_personas
      host: localhost
      port: 5432
      username: db_user
      password: 3xp4ns10n
      connection_check_threshold: 10
      dbi_params:
          RaiseError: 1
          AutoCommit: 1
          pg_enable_utf8: -1
          pg_server_prepare: 1
          log_queries: 1
   FlashNote:
      queue: key_multiple
      dequeue: when_used
